### ISSUE TITLE
TailwindCSS LSP

### ISSUE THREAD

**Issue by hmajid2301** [aabccd021/tailwindcss-daisyui-nix#1]
Hi,

Thank you, for creating this flake, it has been really useful in setting up my development environment without need JS package manager i.e. `pnpm` and `npm`.

I have a CSS file like this:

```css
@import "tailwindcss";
@source "./internal/transport/http/views/**/*.templ";

@plugin "daisyui" {
  themes: cupcake --default;
}
``` 

But I cannot it to work nicely with the tailwind LSP, unless I have a local `node_modules` with a package.json:

```json
{
    "name": "assets",
    "dependencies": {
        "daisyui": "^5.0.16",
        "tailwindcss": "^4.1.3"
    }
}
```

 I was wondering if you had got it working, perhaps with flake and the Tailwind LSP https://github.com/tailwindlabs/tailwindcss-intellisense/issues.  to get completions via the LSP.

I tried setting `NODE_PATH=/nix/store/qa8nf4158vfy7rhv76blfqwdcb4n74yc-node-dependencies-tailwindcss-daisyui/lib/node_modules`.
If not! No worries, I just thought I'd ask!

Thanks
